#########################
## Sass Lint Config
#########################
rules:
  no-ids: 0
  no-important: 0
  hex-notation:
    - 1
    -
      style: lowercase
  # indentation:
  #   - 1
  #   -
  #     size: tab
  property-sort-order:
    - 0
  class-name-format:
    - 0
  force-element-nesting:
    - 0
  no-mergeable-selectors:
    - 0
  no-qualifying-elements:
    - 0
  no-trailing-whitespace:
    - 0
  shorthand-values:
    - 0
  force-pseudo-nesting:
    - 0
  force-attribute-nesting:
    - 0
  nesting-depth:
    - 0
  indentation:
    - 0